### ISSUE TITLE
App admin landing page

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-travel#35]
For `/admin` route:
- [x] Display list of pages in admin menu
- [x] use [article list](http://webstyleguide.ucdavis.edu/?p=organisms-article-list) with [narrow gutter modifier](http://webstyleguide.ucdavis.edu/?p=atoms-container)
- [x] Instead of the publish date, display a little excerpt about what the page is for - use the SettingsModel
- [x] Ensure that excerpts from SettingsModel are only loaded when the page is active
- [x] instead of a photo, display a brand color background with a centered icon

**Comment by mjwdavis** [comment]
Ready for Review.

**Comment by spelkey-ucd** [comment]
submit a PR please
