### ISSUE TITLE
email content generator service

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-travel#68]
when an admin saves an email body or subject line in the settings, it can contain special keywords representing variables such as the requester's name.

Need a class that will have methods that do all of this substitution, e.g.
```js
emailContent.hydate(content, approvalRequest, reimbursementRequest)
```

**Comment by sbagg** [comment]
I need some clarification and examples on this?  Like examples and outcomes this would be used in?

**Comment by spelkey-ucd** [comment]
```js
// retrieved from settings table
content = `
Hi {{requesterFirstName}},

Your travel, training, or professional development request has been successfully submitted. 
It has been sent to {{nextApprover}} for approval.
`
```

the class `hydrate` method will then fill in the variables in handlebars, and the output will be passed along to the emailer service.
