### ISSUE TITLE
Integrate Keycloak Client

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-travel#7]
- [x] Create a basic public client in keycloak internal realm. You can skip sandbox and go straight to auth.library, since this will be a fairly simple implementation
- [x] Create initial client roles. Off the top of my head, I think they should be `basic-access`, `admin-access`, and `report-access`
- [x] Update `serverConfig.js` file with auth defaults
- [x] Add method to `AccessToken.js` utility class for report access (anyone with admin or report access)

**Comment by mjwdavis** [comment]
Did we decide on any urls, both dev and prod?
